/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: dylan hatcher (https://sketchfab.com/DylanHatcher)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/treasure-island-446c38eec211410388ba09d36d0d69a9
Title: treasure island
*/

import { useGLTF } from '@react-three/drei';
import { Mesh, SkinnedMesh } from 'three';
import useIslandModel from '../../hooks/models/useIslandModel';

export const MainIslandModel = (
  props: JSX.IntrinsicElements['group'] & {
    scale: number;
  },
) => {
  const { nodes, materials, group } = useIslandModel();

  return (
    <group ref={group as any} {...props} dispose={null}>
      <group
        name="Sketchfab_Scene"
        scale={props.scale}
        castShadow
        receiveShadow
      >
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          castShadow
          receiveShadow
        >
          <group
            name="93f504eef39b4fe08a8ff84cecc61f17fbx"
            castShadow
            receiveShadow
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2" castShadow receiveShadow>
              <group name="RootNode" castShadow receiveShadow>
                {/* 땅 */}
                <group
                  name="island_landmass"
                  castShadow
                  receiveShadow
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="island_landmass_island_0"
                    geometry={(nodes.island_landmass_island_0 as Mesh).geometry}
                    material={materials.island}
                    castShadow
                    receiveShadow
                  />
                </group>
                <group
                  name="ocean"
                  position={[0, 3, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                  castShadow
                  receiveShadow
                />
                {/* 아래쪽 바위 중 큰 바위 */}
                <group
                  name="large_rock_"
                  position={[0, -9.428, 0]}
                  rotation={[-1.419, 0, 0.543]}
                  scale={15.213}
                  castShadow
                  receiveShadow
                >
                  <mesh
                    name="large_rock__large_rock_0"
                    geometry={(nodes.large_rock__large_rock_0 as Mesh).geometry}
                    material={materials.large_rock}
                    castShadow
                    receiveShadow
                  />
                </group>
                {/* 오른쪽 상단 오른쪽 돌 */}
                <group
                  name="small_rock"
                  position={[64.054, 11.217, -43.146]}
                  rotation={[-1.303, 0.108, 2.894]}
                  scale={[5.866, 5.841, 2.759]}
                  castShadow
                  receiveShadow
                >
                  <mesh
                    name="small_rock_small_rock_0"
                    geometry={(nodes.small_rock_small_rock_0 as Mesh).geometry}
                    material={materials.small_rock}
                    castShadow
                    receiveShadow
                  />
                </group>
                {/* 바닥에 꽂힌 나무판 */}
                <group
                  name="plank"
                  position={[41.522, -27.113, 23.913]}
                  rotation={[-1.413, 0.2, 0.895]}
                  scale={[5.377, 1.644, 5.377]}
                  castShadow
                  receiveShadow
                >
                  <mesh
                    name="plank_plank_0"
                    geometry={(nodes.plank_plank_0 as Mesh).geometry}
                    material={materials.plank}
                    castShadow
                    receiveShadow
                  />
                </group>
                <group
                  name="barrel"
                  position={[49.274, 6.763, 53.87]}
                  rotation={[Math.PI, 0.616, Math.PI / 2]}
                  scale={100}
                  castShadow
                  receiveShadow
                />
                {/* 갈색 병 */}
                {/* <group
                  name="bottle"
                  position={[52.822, -38.492, 42.798]}
                  rotation={[-1.533, -0.138, -0.037]}
                  scale={4.538}
                  castShadow
                  receiveShadow
                  onClick={() => {
                    handleClick('갈색 병');
                  }}
                >
                  <mesh
                    name="bottle_bottle_0"
                    geometry={(nodes.bottle_bottle_0 as Mesh).geometry}
                    material={materials.bottle}
                    castShadow
                    receiveShadow
                  />
                </group> */}
                <group
                  name="PEARL_OYSTER"
                  castShadow
                  receiveShadow
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hermit_crab"
                  castShadow
                  receiveShadow
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={100}
                />
                <group
                  name="treasure_chest"
                  castShadow
                  receiveShadow
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                {/* 바위 중 아래 바위 */}
                <group
                  name="large_rock_001"
                  position={[-21.894, -32.84, 28.124]}
                  rotation={[-1.672, -0.114, 1.055]}
                  scale={8.826}
                  castShadow
                  receiveShadow
                >
                  <mesh
                    name="large_rock_001_large_rock_0"
                    geometry={
                      (nodes.large_rock_001_large_rock_0 as Mesh).geometry
                    }
                    material={materials.large_rock}
                    castShadow
                    receiveShadow
                  />
                </group>
                {/* 오른쪽 상단에 왼쪽 작은 무언가 */}
                <group
                  name="small_rock003"
                  position={[52.738, 12.321, -48.038]}
                  rotation={[-1.704, 0.071, -0.578]}
                  scale={[2.708, 2.697, 1.274]}
                  castShadow
                  receiveShadow
                >
                  <mesh
                    name="small_rock003_small_rock_0"
                    geometry={
                      (nodes.small_rock003_small_rock_0 as Mesh).geometry
                    }
                    material={materials.small_rock}
                    castShadow
                    receiveShadow
                  />
                </group>
                {/* 왼쪽 상단에 오른쪽 조금 큰 무언가 */}
                <group
                  name="small_rock001"
                  position={[14.559, 11.963, -69.825]}
                  rotation={[-1.457, 0.265, -2.604]}
                  scale={[4.58, 4.56, 2.154]}
                  castShadow
                  receiveShadow
                >
                  <mesh
                    name="small_rock001_small_rock_0"
                    geometry={
                      (nodes.small_rock001_small_rock_0 as Mesh).geometry
                    }
                    material={materials.small_rock}
                    castShadow
                    receiveShadow
                  />
                </group>
                {/* 왼쪽 상단에 왼쪽 작은 무언가 */}
                <group
                  name="small_rock002"
                  position={[-1.056, 14.408, -73.65]}
                  rotation={[-1.704, 0.071, -0.578]}
                  scale={[2.115, 2.106, 0.995]}
                  castShadow
                  receiveShadow
                >
                  <mesh
                    name="small_rock002_small_rock_0"
                    geometry={
                      (nodes.small_rock002_small_rock_0 as Mesh).geometry
                    }
                    material={materials.small_rock}
                    castShadow
                    receiveShadow
                  />
                </group>
                {/* 오른족 상단에 왼쪽 작은 돌맹이 */}
                <group
                  name="small_rock004"
                  position={[52.128, 10.151, -39.13]}
                  rotation={[-1.704, 0.071, -0.578]}
                  scale={[0.982, 0.977, 0.462]}
                  castShadow
                  receiveShadow
                >
                  <mesh
                    name="small_rock004_small_rock_0"
                    geometry={
                      (nodes.small_rock004_small_rock_0 as Mesh).geometry
                    }
                    material={materials.small_rock}
                    castShadow
                    receiveShadow
                  />
                </group>
                <group
                  name="palm_tree"
                  position={[60.297, 12.403, -59.48]}
                  rotation={[-Math.PI / 2, 0.529, 0]}
                  scale={22.417}
                  castShadow
                  receiveShadow
                />
                <group
                  name="palm_tree002"
                  position={[6.212, 12.403, -79.538]}
                  rotation={[-2.046, -0.241, 2.006]}
                  scale={22.417}
                  castShadow
                  receiveShadow
                />
                <group
                  name="seaweed"
                  position={[-17.364, -41.545, 54.083]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                  castShadow
                  receiveShadow
                />
                <group
                  name="seaweed001"
                  position={[2.613, -32.339, 36.627]}
                  rotation={[-Math.PI / 2, 0, 0.987]}
                  scale={63.668}
                  castShadow
                  receiveShadow
                />
                <group
                  name="seaweed002"
                  position={[17.221, -36.751, 66.084]}
                  rotation={[-Math.PI / 2, 0, 2.548]}
                  scale={82.895}
                  castShadow
                  receiveShadow
                />
                {/* 나무통 */}
                <group
                  name="barrel_armature"
                  position={[49.274, 6.763, 53.87]}
                  rotation={[Math.PI, 0.616, Math.PI / 2]}
                  scale={6.375}
                  castShadow
                  receiveShadow
                >
                  <group name="Object_35" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_37"
                      position={[49.274, 6.763, 53.87]}
                      rotation={[Math.PI, 0.616, Math.PI / 2]}
                      scale={100}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_38"
                      geometry={(nodes.Object_38 as SkinnedMesh).geometry}
                      material={materials.barrel}
                      skeleton={(nodes.Object_38 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>

                {/* 보물상자 */}
                <group
                  name="chest_armature"
                  castShadow
                  receiveShadow
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_41" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_1}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_43"
                      castShadow
                      receiveShadow
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <skinnedMesh
                      name="Object_44"
                      geometry={(nodes.Object_44 as SkinnedMesh).geometry}
                      material={materials.cheast}
                      skeleton={(nodes.Object_44 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_45"
                      geometry={(nodes.Object_45 as SkinnedMesh).geometry}
                      material={materials.gems}
                      skeleton={(nodes.Object_45 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_46"
                      geometry={(nodes.Object_46 as SkinnedMesh).geometry}
                      material={materials.coin_volume}
                      skeleton={(nodes.Object_46 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_47"
                      geometry={(nodes.Object_47 as SkinnedMesh).geometry}
                      material={materials.material}
                      skeleton={(nodes.Object_47 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_48"
                      geometry={(nodes.Object_48 as SkinnedMesh).geometry}
                      material={materials.individual_coins}
                      skeleton={(nodes.Object_48 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_49"
                      geometry={(nodes.Object_49 as SkinnedMesh).geometry}
                      material={materials.staff_base}
                      skeleton={(nodes.Object_49 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
                {/* 맨 아래 조개 */}
                <group
                  name="oyster_armature"
                  castShadow
                  receiveShadow
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_55" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_2}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_57"
                      castShadow
                      receiveShadow
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <skinnedMesh
                      name="Object_58"
                      geometry={(nodes.Object_58 as SkinnedMesh).geometry}
                      material={materials.oyster}
                      skeleton={(nodes.Object_58 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
                <group
                  name="seaweed_armature"
                  position={[-17.364, -41.545, 54.083]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                  castShadow
                  receiveShadow
                >
                  <group name="Object_62" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_3}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_64"
                      position={[-17.364, -41.545, 54.083]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_65"
                      geometry={(nodes.Object_65 as SkinnedMesh).geometry}
                      material={materials.seaweed}
                      skeleton={(nodes.Object_65 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
                {/* 바닷물 */}
                <group
                  name="ocean_armature"
                  position={[0, 3, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                  castShadow
                  receiveShadow
                >
                  <group name="Object_92" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_4}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_94"
                      position={[0, 3, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_95"
                      geometry={(nodes.Object_95 as SkinnedMesh).geometry}
                      material={materials.ocean}
                      skeleton={(nodes.Object_95 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
                {/* 오른쪽 나무 */}
                <group
                  name="palm_tree_armature"
                  position={[60.297, 12.403, -59.48]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                  castShadow
                  receiveShadow
                >
                  <group name="Object_135" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_5}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_137"
                      position={[60.297, 12.403, -59.48]}
                      rotation={[-Math.PI / 2, 0.529, 0]}
                      scale={22.417}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_138"
                      geometry={(nodes.Object_138 as SkinnedMesh).geometry}
                      material={materials.palm_tree}
                      skeleton={(nodes.Object_138 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_139"
                      geometry={(nodes.Object_139 as SkinnedMesh).geometry}
                      material={materials.palm_tree_leaves}
                      skeleton={(nodes.Object_139 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
                <group
                  name="hermit_crab_armature"
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={100}
                  castShadow
                  receiveShadow
                >
                  <group name="Object_252" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_6}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_254"
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                      scale={100}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_255"
                      geometry={(nodes.Object_255 as SkinnedMesh).geometry}
                      material={materials.hermit_crab}
                      skeleton={(nodes.Object_255 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
                {/* 왼쪽 나무  */}
                <group
                  name="palm_tree_armature002"
                  position={[6.212, 12.403, -79.538]}
                  rotation={[-Math.PI / 2, 0, 2.064]}
                  scale={100}
                  castShadow
                  receiveShadow
                >
                  <group name="Object_327" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_7}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_329"
                      position={[6.212, 12.403, -79.538]}
                      rotation={[-2.046, -0.241, 2.006]}
                      scale={22.417}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_330"
                      geometry={(nodes.Object_330 as SkinnedMesh).geometry}
                      material={materials.palm_tree}
                      skeleton={(nodes.Object_330 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_331"
                      geometry={(nodes.Object_331 as SkinnedMesh).geometry}
                      material={materials.palm_tree_leaves}
                      skeleton={(nodes.Object_331 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
                <group
                  name="seaweed_armature001"
                  position={[2.613, -32.339, 36.627]}
                  rotation={[-Math.PI / 2, 0, 0.987]}
                  scale={63.668}
                  castShadow
                  receiveShadow
                >
                  <group name="Object_444" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_8}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_446"
                      position={[2.613, -32.339, 36.627]}
                      rotation={[-Math.PI / 2, 0, 0.987]}
                      scale={63.668}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_447"
                      geometry={(nodes.Object_447 as SkinnedMesh).geometry}
                      material={materials.seaweed}
                      skeleton={(nodes.Object_447 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
                <group
                  name="seaweed_armature002"
                  position={[17.221, -36.751, 66.084]}
                  rotation={[-Math.PI / 2, 0, 2.548]}
                  scale={82.895}
                  castShadow
                  receiveShadow
                >
                  <group name="Object_474" castShadow receiveShadow>
                    <primitive
                      object={nodes._rootJoint_9}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_476"
                      position={[17.221, -36.751, 66.084]}
                      rotation={[-Math.PI / 2, 0, 2.548]}
                      scale={82.895}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_477"
                      geometry={(nodes.Object_477 as SkinnedMesh).geometry}
                      material={materials.seaweed}
                      skeleton={(nodes.Object_477 as SkinnedMesh).skeleton}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/island2/scene.gltf');
